name: aws_tgw_route_monitor
# label used for menu selection
label: AWS Transit Gateway Firewalls Step 2 Show Routes

description: >
  We achieve HA with routing table updates in the Security VPC.
  This page will show the current route table of interest

# type of skillet (panos or panorama or template or terraform)
type: python3

# more complex skillets may express a dependency on another skillet that should be loaded before this one.
# For example, a set of skillets may build off of a single 'golden config' that contains shared configuration
# As this skillet is very simple, there is no need to build on another one.
extends:

# Labels allow grouping and type specific options and are generally only used in advanced cases
labels:
  collection: AWS Transit Gateway Direct Attached Firewalls

# variables define the things an operator may customize in this skillet. Things like DNS servers, NTP addresses, etc
# may be customized for each deployment. Each variable will be rendered as a form field in the panhandler application
variables:
  - name: aws_access_key
    description: AWS Access Key
    default: abc123
    type_hint: text
  - name: aws_secret_key
    description: AWS Secret Key
    default:
    type_hint: password
  - name: aws_region
    description: AWS Region
    default: us-east-2
    type_hint: text

# Snippets is an ordered list of configuration xml fragments that will be pushed to the PAN-OS NGFW. The xpath
# determines where in the configuration hierarchy the xml fragment will be set. 'file' indicates the name of the file
# to load and parse. Jinja2 style variables will be variable interpolated using the values of the 'variables' defined
# in the 'variables' section.
snippets:
  - name: script
    file: ../../check-direct-routes.py
#    output_type:
#    outputs:
#      - name: app_threat_version
#        capture_pattern: result/content-updates/entry/version
